/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface AppSidemenu {
    }
    interface PageDashboard {
    }
    interface PageForm {
        "history"?: RouterHistory;
    }
    interface PageLogin {
        "history"?: RouterHistory;
    }
    interface PageProdiList {
    }
    interface PageProfile {
    }
    interface PageRegister {
        "history"?: RouterHistory;
    }
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSidemenuElement extends Components.AppSidemenu, HTMLStencilElement {
    }
    var HTMLAppSidemenuElement: {
        prototype: HTMLAppSidemenuElement;
        new (): HTMLAppSidemenuElement;
    };
    interface HTMLPageDashboardElement extends Components.PageDashboard, HTMLStencilElement {
    }
    var HTMLPageDashboardElement: {
        prototype: HTMLPageDashboardElement;
        new (): HTMLPageDashboardElement;
    };
    interface HTMLPageFormElement extends Components.PageForm, HTMLStencilElement {
    }
    var HTMLPageFormElement: {
        prototype: HTMLPageFormElement;
        new (): HTMLPageFormElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageProdiListElement extends Components.PageProdiList, HTMLStencilElement {
    }
    var HTMLPageProdiListElement: {
        prototype: HTMLPageProdiListElement;
        new (): HTMLPageProdiListElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPageRegisterElement extends Components.PageRegister, HTMLStencilElement {
    }
    var HTMLPageRegisterElement: {
        prototype: HTMLPageRegisterElement;
        new (): HTMLPageRegisterElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-root": HTMLAppRootElement;
        "app-sidemenu": HTMLAppSidemenuElement;
        "page-dashboard": HTMLPageDashboardElement;
        "page-form": HTMLPageFormElement;
        "page-login": HTMLPageLoginElement;
        "page-prodi-list": HTMLPageProdiListElement;
        "page-profile": HTMLPageProfileElement;
        "page-register": HTMLPageRegisterElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface AppSidemenu {
    }
    interface PageDashboard {
    }
    interface PageForm {
        "history"?: RouterHistory;
    }
    interface PageLogin {
        "history"?: RouterHistory;
    }
    interface PageProdiList {
    }
    interface PageProfile {
    }
    interface PageRegister {
        "history"?: RouterHistory;
    }
    interface IntrinsicElements {
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-root": AppRoot;
        "app-sidemenu": AppSidemenu;
        "page-dashboard": PageDashboard;
        "page-form": PageForm;
        "page-login": PageLogin;
        "page-prodi-list": PageProdiList;
        "page-profile": PageProfile;
        "page-register": PageRegister;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-sidemenu": LocalJSX.AppSidemenu & JSXBase.HTMLAttributes<HTMLAppSidemenuElement>;
            "page-dashboard": LocalJSX.PageDashboard & JSXBase.HTMLAttributes<HTMLPageDashboardElement>;
            "page-form": LocalJSX.PageForm & JSXBase.HTMLAttributes<HTMLPageFormElement>;
            "page-login": LocalJSX.PageLogin & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-prodi-list": LocalJSX.PageProdiList & JSXBase.HTMLAttributes<HTMLPageProdiListElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "page-register": LocalJSX.PageRegister & JSXBase.HTMLAttributes<HTMLPageRegisterElement>;
        }
    }
}
